name: Post-Deployment Actions

on:
  push:
    branches:
      - backend
  deployment_status:
    states: [success]

jobs:
  post-deploy:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - name: Debug - Print folder contents
        run: |
          echo "The working folder contains: "
          echo $(ls)
          
      # Only run if this is a production environment deployment that succeeded
      - name: Run post-deploy actions
        if: github.event.deployment.environment == 'production'
        run: |
          echo "Production deployment succeeded"
          cd .. && python injest.py